server:
  port: 10010
spring:
  cloud:
    gateway:
      routes:
        - id: provider-service
          uri: lb://provider-service
          order: 0
          predicates:
            - Path=/sell/provider_service/**
          filters:
            - StripPrefix=2

        - id: consumer-service
          uri: lb://consumer-service
          order: 0
          predicates:
            - Path=/sell/consumer_service/**
          filters:
            - StripPrefix=2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka